# Link repository with Travis CI
# https://travis-ci.org/

branches:
  only:
    - master

cache:
  - pip

language: bash

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH

before_install:
  # Install TeX Live
  - sudo apt-get update -qq
  - sudo apt-get install texlive-full
  - sudo apt-get install haskell-platform
  #- cabal update
  #- cabal install pandoc-1.17.2 pandoc-citeproc pandoc-crossref
  - wget https://github.com/jgm/pandoc/releases/download/1.17.2/pandoc-1.17.2-1-amd64.deb && ar p pandoc-1.17.2-1-amd64.deb data.tar.gz | tar zx
  - sudo pip install pandoc-eqnos pandoc-shortcaption
  - sudo apt-get install lmodern
  - git clone https://github.com/citation-style-language/styles.git $TRAVIS_BUILD_DIR/../styles
  - pwd
  - ls

# Attempt to create a PDF
script:
  - make -C example/master_thesis/
